name = "PlasmaFluidSim"
uuid = "d4f8a365-2de5-47fe-b75b-f2dc583f8f12"
authors = ["Jan Kuhfeld <jan.kuhfeld@rub.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
